version: "3.7"
services:
    mongo:
        image: mongo
        volumes: 
          - database:/data/db
        restart: always
        command: [--auth]
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
          - 8082:8082

    server:
        image: repository
        build:    
          context: .
          dockerfile: Dockerfile
        ports:
          - 8081:8081
          - 35730:35730
        depends_on:
          - mongo
volumes:
  database: